/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFunnelsRouteImport } from './routes/app.funnels'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminTestRouteImport } from './routes/app.admin-test'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWidgetEmbedDotjsRouteImport } from './routes/api/public/widget/embed[.]js'
import { Route as ApiPublicWidgetChatRouteImport } from './routes/api/public/widget/chat'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron.tick'
import { Route as ApiPublicAdminTestSendRouteImport } from './routes/api/public/admin-test/send'
import { Route as ApiPublicMetaLeadsWebhookRouteImport } from './routes/api/public/meta/leads/webhook'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFunnelsRoute = AppFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTestRoute = AppAdminTestRouteImport.update({
  id: '/admin-test',
  path: '/admin-test',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetEmbedDotjsRoute =
  ApiPublicWidgetEmbedDotjsRouteImport.update({
    id: '/api/public/widget/embed.js',
    path: '/api/public/widget/embed.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetChatRoute = ApiPublicWidgetChatRouteImport.update({
  id: '/api/public/widget/chat',
  path: '/api/public/widget/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminTestSendRoute = ApiPublicAdminTestSendRouteImport.update({
  id: '/api/public/admin-test/send',
  path: '/api/public/admin-test/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaLeadsWebhookRoute =
  ApiPublicMetaLeadsWebhookRouteImport.update({
    id: '/api/public/meta/leads/webhook',
    path: '/api/public/meta/leads/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/admin': typeof AppAdminRoute
  '/app/admin-test': typeof AppAdminTestRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/funnels': typeof AppFunnelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/training': typeof AppTrainingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/admin-test/send': typeof ApiPublicAdminTestSendRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/meta/leads/webhook': typeof ApiPublicMetaLeadsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/admin': typeof AppAdminRoute
  '/app/admin-test': typeof AppAdminTestRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/funnels': typeof AppFunnelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/training': typeof AppTrainingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/admin-test/send': typeof ApiPublicAdminTestSendRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/meta/leads/webhook': typeof ApiPublicMetaLeadsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/admin': typeof AppAdminRoute
  '/app/admin-test': typeof AppAdminTestRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/funnels': typeof AppFunnelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/training': typeof AppTrainingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/admin-test/send': typeof ApiPublicAdminTestSendRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/meta/leads/webhook': typeof ApiPublicMetaLeadsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/unsubscribe'
    | '/app/admin'
    | '/app/admin-test'
    | '/app/analytics'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/funnels'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/settings'
    | '/app/templates'
    | '/app/training'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/api/public/admin-test/send'
    | '/api/public/cron/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/widget/chat'
    | '/api/public/widget/embed.js'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/meta/leads/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/unsubscribe'
    | '/app/admin'
    | '/app/admin-test'
    | '/app/analytics'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/funnels'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/settings'
    | '/app/templates'
    | '/app/training'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/api/public/admin-test/send'
    | '/api/public/cron/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/widget/chat'
    | '/api/public/widget/embed.js'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/meta/leads/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/unsubscribe'
    | '/app/admin'
    | '/app/admin-test'
    | '/app/analytics'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/funnels'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/settings'
    | '/app/templates'
    | '/app/training'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/api/public/admin-test/send'
    | '/api/public/cron/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/widget/chat'
    | '/api/public/widget/embed.js'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/meta/leads/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicAdminTestSendRoute: typeof ApiPublicAdminTestSendRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicWidgetChatRoute: typeof ApiPublicWidgetChatRoute
  ApiPublicWidgetEmbedDotjsRoute: typeof ApiPublicWidgetEmbedDotjsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicMetaLeadsWebhookRoute: typeof ApiPublicMetaLeadsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funnels': {
      id: '/app/funnels'
      path: '/funnels'
      fullPath: '/app/funnels'
      preLoaderRoute: typeof AppFunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin-test': {
      id: '/app/admin-test'
      path: '/admin-test'
      fullPath: '/app/admin-test'
      preLoaderRoute: typeof AppAdminTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/embed.js': {
      id: '/api/public/widget/embed.js'
      path: '/api/public/widget/embed.js'
      fullPath: '/api/public/widget/embed.js'
      preLoaderRoute: typeof ApiPublicWidgetEmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/chat': {
      id: '/api/public/widget/chat'
      path: '/api/public/widget/chat'
      fullPath: '/api/public/widget/chat'
      preLoaderRoute: typeof ApiPublicWidgetChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-test/send': {
      id: '/api/public/admin-test/send'
      path: '/api/public/admin-test/send'
      fullPath: '/api/public/admin-test/send'
      preLoaderRoute: typeof ApiPublicAdminTestSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/leads/webhook': {
      id: '/api/public/meta/leads/webhook'
      path: '/api/public/meta/leads/webhook'
      fullPath: '/api/public/meta/leads/webhook'
      preLoaderRoute: typeof ApiPublicMetaLeadsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAdminTestRoute: typeof AppAdminTestRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFunnelsRoute: typeof AppFunnelsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTrainingRoute: typeof AppTrainingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAdminTestRoute: AppAdminTestRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFunnelsRoute: AppFunnelsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTrainingRoute: AppTrainingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicAdminTestSendRoute: ApiPublicAdminTestSendRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicWidgetChatRoute: ApiPublicWidgetChatRoute,
  ApiPublicWidgetEmbedDotjsRoute: ApiPublicWidgetEmbedDotjsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicMetaLeadsWebhookRoute: ApiPublicMetaLeadsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
