/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppFunnelsRouteImport } from './routes/app.funnels'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron.tick'
import { Route as ApiPublicMetaLeadsWebhookRouteImport } from './routes/api/public/meta/leads/webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFunnelsRoute = AppFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaLeadsWebhookRoute =
  ApiPublicMetaLeadsWebhookRouteImport.update({
    id: '/api/public/meta/leads/webhook',
    path: '/api/public/meta/leads/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/funnels': typeof AppFunnelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/training': typeof AppTrainingRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/meta/leads/webhook': typeof ApiPublicMetaLeadsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/funnels': typeof AppFunnelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/training': typeof AppTrainingRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/meta/leads/webhook': typeof ApiPublicMetaLeadsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/funnels': typeof AppFunnelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/training': typeof AppTrainingRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/meta/leads/webhook': typeof ApiPublicMetaLeadsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/funnels'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/settings'
    | '/app/templates'
    | '/app/training'
    | '/api/public/cron/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/meta/leads/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/funnels'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/settings'
    | '/app/templates'
    | '/app/training'
    | '/api/public/cron/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/meta/leads/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/funnels'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/settings'
    | '/app/templates'
    | '/app/training'
    | '/api/public/cron/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/meta/leads/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicMetaLeadsWebhookRoute: typeof ApiPublicMetaLeadsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funnels': {
      id: '/app/funnels'
      path: '/funnels'
      fullPath: '/app/funnels'
      preLoaderRoute: typeof AppFunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/leads/webhook': {
      id: '/api/public/meta/leads/webhook'
      path: '/api/public/meta/leads/webhook'
      fullPath: '/api/public/meta/leads/webhook'
      preLoaderRoute: typeof ApiPublicMetaLeadsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFunnelsRoute: typeof AppFunnelsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTrainingRoute: typeof AppTrainingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFunnelsRoute: AppFunnelsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTrainingRoute: AppTrainingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicMetaLeadsWebhookRoute: ApiPublicMetaLeadsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
